services:
  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
  redis:
    image: redis
    ports:
      - "6379:6379"
  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: "amqp://user:password@rabbitmq:5672"
    depends_on:
      - rabbitmq
