# Generated by Django 5.1.4 on 2024-12-31 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Url do Video')),
                ('title', models.CharField(max_length=400, verbose_name='Nome do Video')),
                ('channel', models.CharField(max_length=200, verbose_name='Nome do Canal do Video')),
                ('file', models.CharField(blank=True, max_length=200, null=True, verbose_name='Downloaded File')),
                ('status', models.CharField(choices=[('000', 'New'), ('100', 'In Process'), ('200', 'Processed'), ('900', 'Error')], default='000', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DurationField(verbose_name='Start Time Chapter')),
                ('end_time', models.DurationField(verbose_name='End Time Chapter')),
                ('title', models.CharField(max_length=400, verbose_name='Nome do Capitulo')),
                ('status', models.CharField(choices=[('000', 'New'), ('100', 'In Process'), ('200', 'Processed'), ('900', 'Error')], default='000', max_length=15)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tupi_clip.video')),
            ],
        ),
    ]
